### ISSUE TITLE
Change Mobs

### ISSUE THREAD

**Issue by Resoluciones** [rodel77/Invasion#5]
Hi!  How do you change mob types?

Thanks!

**Comment by rodel77** [comment]
Check the "mobs:" section in the config and then edit the "entity:" node on the mod you want, you can check the types here: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/EntityType.html

**Comment by Resoluciones** [comment]
Hi, thanks for the reply!

I've changed them several times, i.e. https://hasteb.in/gopinida.sm

But when I do /invasion start [PLAYER] the mobs are different (zombies mainly).

Can you pls. let me know what am I doing wrong?

Thanks!

**Comment by rodel77** [comment]
This code is very old, and very hard to read right now but i think i saw that the config is implemented but you can't change the mob type, i will release an update with some grammar fixes now but probably for this issue i will need to make a big refactor, stay tunned to this issue i will post there any update about that
